# Generated by Django 4.2.1 on 2023-06-04 08:23

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_timeline_bordercolor_timeline_bgcolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='titleColor',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
