# Generated by Django 4.2.1 on 2023-06-04 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_timeline_titlecolor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeline',
            old_name='BorderColor',
            new_name='borderColor',
        ),
    ]
