# Generated by Django 4.2.1 on 2023-06-07 07:39

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_timeline_bgcolor_alter_timeline_bordercolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bgColor',
            field=colorfield.fields.ColorField(default='#f8f9fa', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='item',
            name='titleColor',
            field=colorfield.fields.ColorField(default='#343a40', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
