# Generated by Django 4.2.1 on 2023-06-07 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_item_bgcolor_item_titlecolor_item_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='type',
            new_name='typeOfItem',
        ),
    ]
