# Generated by Django 4.2.1 on 2023-06-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_type_item_typeofitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='endDate',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='startDate',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='typeOfItem',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='bgColor',
        ),
        migrations.RemoveField(
            model_name='item',
            name='titleColor',
        ),
    ]
