# Generated by Django 4.2.1 on 2023-06-10 16:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_enddate_item_end_rename_startdate_item_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='style',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
