# Generated by Django 4.2.1 on 2023-06-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_item_style_alter_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='style',
        ),
        migrations.AddField(
            model_name='item',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
