# Generated by Django 4.2.1 on 2023-06-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_item_content_alter_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='selectable',
            field=models.BooleanField(default=True),
        ),
    ]
