# Generated by Django 4.2.1 on 2023-06-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_item_selectable'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='notesDetails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='style',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
