# Generated by Django 4.2.1 on 2023-06-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_timeline_bgcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='bgColor',
            field=models.CharField(default='#30303034', max_length=9),
        ),
    ]
