# Generated by Django 4.2.1 on 2023-06-19 18:40

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_timeline_bgcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='bgColor',
            field=colorfield.fields.ColorField(default='#f8f9fa', image_field=None, max_length=18, samples=None),
        ),
    ]
