# Generated by Django 4.2.1 on 2023-07-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_item_bgcolor_item_bordercolor_item_fonstsize_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='fonstSize',
            new_name='fontSize',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='fonstStyle',
            new_name='fontStyle',
        ),
    ]
